In [9]:
import pandas as pd
import numpy as np
from scipy.stats import moment
import matplotlib.pyplot as plt
import math
import scipy.stats as sp
from scipy.stats import norm

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [17]:
data_be32 = pd.read_csv('/content/drive/MyDrive/Important Folders & Files/BT2022/data_part1.csv')
data_be32.info()
data_be32.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
dtypes: float64(1)
memory usage: 1.3 KB


0
0  10.42580
1   2.61849
2   7.97376
3  13.57810
4   8.47175

In [18]:
data = data_be32.to_numpy()
data.shape

(150, 1)

In [19]:
m1 = np.mean(data)
m2 = moment(data - m1, moment=2)
m3 = moment(data - m1, moment=3)
m4 = moment(data - m1, moment=4)

print(f"First moment (sample mean): {1}")
print(f"Second moment: {m2}")
print(f"Third moment: {m3}")
print(f"Fourth moment: {m4}")

First moment (sample mean): 1
Second moment: [16.64853872]
Third moment: [108.96317232]
Fourth moment: [1769.6071078]


In [20]:
beta_1 = np.power(m3,2) / np.power(m2,3) #skewness
beta_2 = m4 / np.power(m2,2)   #kurtosis
classification_term = m3 / (m2 ** 1.5)
print(beta_1)
print(beta_2)
print(f"Classification term: {classification_term}")

[2.57294863]
[6.38446651]
Classification term: [1.60404134]


In [21]:
data_be32_q2 = pd.read_csv('/content/drive/MyDrive/Important Folders & Files/BT2022/data_part2.csv')
data_be32_q2.info()
data_be32_q2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       120 non-null    int64
 1   1       120 non-null    int64
 2   2       120 non-null    int64
 3   3       120 non-null    int64
 4   4       120 non-null    int64
 5   5       120 non-null    int64
 6   6       120 non-null    int64
 7   7       120 non-null    int64
 8   8       120 non-null    int64
 9   9       120 non-null    int64
dtypes: int64(10)
memory usage: 9.5 KB


0    1   2    3   4    5    6    7    8    9
0   84   67  20   82  65   14   28   85   12   61
1   65   89  60  125  94   66   98   40  103  132
2  142  116  68   22  79   90  105   66   84   55
3   16  143  36   49  15   94   66  107  105  133
4   19  123  56   61   9  125   87  135    2   73

In [22]:
data_q2 = data_be32_q2.to_numpy()
print(data_q2)
data_be32_q2 = np.random.rand(120,10)
for i in range(120):
    for j in range(10):
        data_be32_q2[i][j] = data[data_q2[i][j]]
print(data_be32_q2)               

[[ 84  67  20 ...  85  12  61]
 [ 65  89  60 ...  40 103 132]
 [142 116  68 ...  66  84  55]
 ...
 [ 66 129 143 ...  85 106  61]
 [102 148  96 ... 146 125  12]
 [ 48  41   8 ...  65 118  62]]
[[ 0.0960029  6.05781    2.83444   ...  4.77497   10.8532     6.32876  ]
 [ 5.97183    1.19016    1.206     ...  1.00949    3.9117     1.12634  ]
 [ 9.94511    7.86225    0.373814  ...  2.27173    0.0960029  3.9982   ]
 ...
 [ 2.27173    3.01368    6.04456   ...  4.77497    1.43914    6.32876  ]
 [ 3.10788    2.52242    0.130873  ... 19.0792     4.29719   10.8532   ]
 [ 6.71841    7.3944     7.49608   ...  5.97183    1.96936    0.0855183]]


In [23]:
z = np.sum(data_be32_q2,axis = 1)/np.sqrt(10)
print(z)

[15.30212432 10.67441086 11.25933258 12.52455409 17.22789232 19.76571216
 10.65672674 12.68668296 16.20950008 13.42504409 14.49635441 14.78865521
  7.16165259  4.90237344 13.3694835  15.78465314 16.45532923 14.11637617
 16.51558421 10.46590988  9.50557833 17.38762845 11.70526509 14.59367293
 19.00670322  9.22254721 11.15348612 10.37774023 10.85769183 14.39404375
 14.54462825 14.8427504  12.33528535 11.90760238 11.1004367  22.00301503
 15.60473346 18.74980168 17.39754978 12.42710069 17.75618432  9.87510755
 17.93724495  7.92868261 13.54122803 11.14588442 15.03999089 19.150005
 16.64441699 12.524287   19.68095679 15.3727728   9.81885411 13.02955446
  9.47540166 13.99655019 15.01144937 14.13905274  8.31465947 19.62752442
 10.90102967 11.09703665 12.7962394  14.01397814 14.07621587 19.51300507
 16.54420469 14.21116639 14.50917501  6.60718136 10.05340277 18.33646037
 21.80828738 18.60818193 16.72027054 12.76545937  7.28288483 11.34472297
 14.86390983 15.85837311 13.20460712 11.04669696 16.1

In [31]:
mz = np.mean(z)
sz = np.std(z)
alpha = 0.0180062
l = len(z)
n = math.sqrt(l)

t = sp.t.ppf(q = alpha/2, df = l - 1)
sigma = sz/n
error_margin = sigma*abs(t)
interval = ((mz - error_margin)/np.sqrt(10), (mz + error_margin)/np.sqrt(10))
print(interval)

(4.157371888417981, 4.635356589415351)


In [27]:
chi1 = sp.chi2.ppf(q = alpha/2, df = l - 1)
chi2 = sp.chi2.ppf(q = 1 - (alpha/2), df = l - 1)
nu = len(z)-1
lower = (nu*np.var(z))/chi2
upper = (nu*np.var(z))/chi1
print((lower, upper))

(8.942024464085222, 16.56237326611661)
